# -*- coding: utf-8 -*-
"""
Created on Tue Apr 15 17:54:09 2025

canbus
------

Module for decoding data logs from the CAN bus. 

This code is partially copied from the bicycle_loc_and_state repo created by
Anna Marbus during her Master's Thesis. Original code by Anna Marbus.
Copying and modifications by Christoph Konrad.
https://repository.tudelft.nl/record/uuid:092f3b70-2d97-436e-b193-139a593e09c7

@author: Anna Marbus
@author: Christoph M. Konrad
"""


import os
import pandas as pd


def process_can(filepath_log, filepath_dbc):
    """ Decode can log file and convert to dataframe."""

    if filepath_log.lower().endswith('.txt'):
        return process_can_cl2000(filepath_dbc, filepath_log)
    elif filepath_log.lower().endswith('.mf4'):
        database = {"LIN": [(filepath_dbc, 0)], "CAN": [(filepath_dbc, 0)]}
        return process_can_edge([filepath_log], database)
    else:
        raise TypeError(f"The can log file must be either '.txt' or '.mf4'. Instead it was {filepath_log}")


def process_can_edge(logfiles, databases):
    """
    This function processes CAN log files using DBC files to decode the 
    messages.
    
    ONLY SUPPORTS LOGS CREATED BY THE CAN Edge 2 LOGGER!

    Copied from the bicycle_loc_and_state repo created by Anna Marbus

    Parameters
    ----------
    
    logfiles : list 
        List of paths to the MDF log files.
    databases : dict
        Dictionary containing the bus types as keys and a list of tuples with 
        DBC file paths and corresponding channel numbers as values.
    
    Returns
    -------
    df_can_edge : pandas.dataframe
        Dataframe of the can decoded can log
    """
    # Concatenate the MDF log files
    try:
        import asammdf
    except ModuleNotFoundError as e:
        e.add_note("Re-install sensorbike with optional dependencies to enable decoding CANEdge2 logs: pip install .[canedge2] or or pip install .[cl2000,canedge2]")
        raise e
    mdf = asammdf.MDF.concatenate(logfiles)
    
    # Extract bus logging data using the specified databases
    mdf_scaled = mdf.extract_bus_logging(databases)
    
    # Covert to dataframe. use_interpolation enforces a joint time grid. 
    df_can_edge = mdf_scaled.to_dataframe(use_interpolation=True,
                                          time_as_date=True)
    
    return df_can_edge


def verify_filepath_dbc(filepath):
    """ Check if the given filepath points to a .dbc file.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"Can't find file {filepath}.")
    elif not filepath.lower().endswith('.dbc'):
        raise TypeError(f"File {filepath} is not a .dbc file.")
    else:
        return filepath
    

def verify_filepath_mf4(filepath):
    """ Check if the given filepath points to a .mf4 file.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"Can't find file {filepath}.")
    elif not filepath.lower().endswith('.mf4'):
        raise TypeError(f"File {filepath} is not a .mf4 file.")
    else:
        return filepath
    

def verify_filepath_txt(filepath):
    """ Check if the given filepath points to a .txt can log generated by the CL2000 logger.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"Can't find file {filepath}.")
    elif not filepath.lower().endswith('.txt'):
        raise TypeError(f"File {filepath} is not a .txt file.")
    else:
        with open(filepath, 'r') as f:
            for i in range(16):
                line = f.readline()
                if 'CL2000' in line:
                    return filepath
        raise TypeError(f"File {filepath} is not a can log generated by the CL2000 logger.")
    

def verify_filepath_can(filepath):
    """ Check if a given filepath is a .mf4 or .txt log generated by the CL2000 logger.
    """
    try:
        return verify_filepath_mf4(filepath)
    except TypeError:
        pass

    try:
        return verify_filepath_txt(filepath)
    except TypeError:
        pass

    raise TypeError(f"File {filepath} is neither a '.mf4' can log generated by the CANEdge2 logger nor a '.txt' can log generated by the CL2000 logger.")
    

def list_canlogs(directory, verbose=False, nonrecursive=False, ignoreexisiting=False, filetypes_out=['.csv', '.parquet']):
    """ List all CAN log files (ending with .mf4) in 
    a given directory and its subdirectories.

    Parameters
    ----------
    directory : str
        The directory to look in.
    verbose : bool, optional
        Print log file list, default is False.
    nonrecursive : bool, optional
        Perform non-recursive search instead of going through all 
        subdirectories. Default is False.
    ignoreexisting : bool, optional
        Ignore logs for which a decoded file already exists.
    filetypes_out : list, optional
        List of output filetypes used to check for existing decoded files.
        Default is ['.csv', '.parquet'].
    
    Returns
    -------
    logfiles_mf4 : list
        List of paths to all mf4 can log files (CANEdge2) in the directory.
    logfiles_txt : list
        List of paths to all txt can log files (CL2000) in the directory.

    """
    ignored = 0

    def extracted_exists(can_filepath):
        nonlocal ignored
        if ignoreexisiting:
            for ftype in filetypes_out:
                if os.path.isfile(os.path.splitext(can_filepath)[0]+ftype):
                    ignored += 1
                    return True
        return False

    logfiles_mf4 = []
    logfiles_txt = []
    for root, _, files in os.walk(directory):
        for file in files:
            if file.lower().endswith('.mf4'):
                full_path = os.path.join(root, file)
                relative_path = os.path.relpath(full_path, directory)
                if not extracted_exists(full_path):
                    logfiles_mf4.append(relative_path)
            if file.lower().endswith('.txt'):
                try:
                    full_path = verify_filepath_txt(os.path.join(root, file))
                except TypeError:
                    continue
                relative_path = os.path.relpath(full_path, directory)
                if not extracted_exists(full_path):
                    logfiles_txt.append(relative_path)
        if nonrecursive:
            break

    logfiles_mf4 = sorted(logfiles_mf4)
    logfiles_txt = sorted(logfiles_txt)
    
    if verbose:
        print(f'Found {len(logfiles_mf4)} CAN Edge 2 logs in {directory}:')
        for i, f in enumerate(logfiles_mf4):
            print(f'    {i:<3}: {f}')
        print(f'Found {len(logfiles_txt)} CAN CL2000 logs in {directory}:')
        for i, f in enumerate(logfiles_txt):
            print(f'    {i:<3}: {f}')
        if ignoreexisiting and ignored > 0:
            print(f'Ignored {ignored} logs with existing decoded files of types {filetypes_out}.')
    
    return logfiles_mf4, logfiles_txt


def process_can_cl2000(dbc_file, log_file):
    """
    This function processes CAN log files using DBC files to decode the 
    messages.
    
    ONLY SUPPORTS LOGS CREATED BY THE CL2000 CAN logger!

    Parameters
    ----------
    
    dbc_file :
        Path to the bus definition (.dbc)

    log_file : list 
        Paths to the TXT log file.
    
    Returns
    -------
    df_log : pandas.dataframe
        Dataframe of the can decoded can log
    """
    
    # Load the DBC file
    try:
        import cantools
    except ModuleNotFoundError as e:
        e.add_note("Re-install sensorbike with optional dependencies to enable decoding CL2000 logs: pip install .[cl2000] or pip install .[cl2000,canedge2]")
        raise 
    
    db = cantools.database.load_file(dbc_file)

    # converters for reading the txt log
    def hex2int(x):
        try:
            return int(x, 16)
        except ValueError:
            return None

    def hex2bytes(x):
        try:
            return bytes.fromhex(x)
        except ValueError:
            return None

    df_log = pd.read_csv(log_file, sep=';', comment='#', 
                     parse_dates=['Timestamp'], date_format=r'%Y/%m/%d:%H:%M:%S:%f',
                     converters={
                        'ID': hex2int,
                        'Data': hex2bytes
                     })
    
    # drop messages not corresponding to the kinematics
    kinematic_ids = [66, 67, 68, 71, 342]
    df_log = df_log[df_log['ID'].isin(kinematic_ids)]
    
    # decode messages
    decoded_messages = []
    for id_, data in zip(df_log['ID'], df_log['Data']):
        try:
            decoded_messages.append(db.decode_message(id_, data))
        except Exception:
            decoded_messages.append(None)
    df_log['message'] = decoded_messages
    df_log = df_log[df_log['message'].notnull()]

    # extract message dicts
    expanded_df = pd.DataFrame.from_records(df_log['message'].tolist(), index=df_log.index)
    df_log = pd.concat([df_log['Timestamp'], expanded_df], axis=1)
    df_log = df_log.groupby('Timestamp').first().reset_index()

    return df_log


def rename_canlog_columns(df):
    """ Rename the can-log columns to more descriptive names incl. units.
    """
    MEASUREMENTS_TO_EXTRACT = {
        'gyro_z': 'gyro_z_rad/s',
        'gyro_y': 'gyro_y_rad/s',
        'gyro_x': 'gyro_x_rad/s',
        'accel_z': 'accel_z_m/s2', 
        'accel_y': 'accel_y_m/s2',
        'accel_x': 'accel_x_m/s2',
        'yaw': 'yaw_rad',
        'pitch': 'pitch_rad',
        'roll': 'roll_rad',
        'ws_rear': 'wheelspeed_rear_rev/s',
        'LWS_ANGLE': 'steer_deg',
        'LWS_SPEED': 'steer_rate_deg/s',
    }

    df = df[list(MEASUREMENTS_TO_EXTRACT.keys())]
    df = df.rename(MEASUREMENTS_TO_EXTRACT)
    return df


def decode_parquet(logfile):
    """ Decode a parquet CAN log file.

    Parameters
    ----------
    logfile : str
        Filepath of the CAN log file

    Returns
    -------
    df : DataFrame
        Logs
    """

    df = pd.read_parquet(logfile)

    keys = {
        'gyro_z_rad/s': 'gyro_z',
        'gyro_y_rad/s': 'gyro_y',
        'gyro_x_rad/s': 'gyro_x', 
        'accel_z_m/s2': 'accel_z', 
        'accel_y_m/s2': 'accel_y', 
        'accel_x_m/s2': 'accel_x', 
        'yaw_rad': 'yaw', 
        'pitch_rad': 'pitch', 
        'roll_rad': 'roll', 
        'wheelspeed_rear_rev/s': 'ws_rear', 
        'steer_deg': 'LWS_ANGLE', 
        'steer_rate_deg/s': 'LWS_SPEED'}
    
    df.rename(columns=keys, inplace=True)

    return df


