[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sensorbike"
description = "Load and filter data collected from the Gazelle/Bosch Balance Assist Bicycles"
readme = "README.md"
version = "2.0.7"
license = {file = "LICENSE"}
authors = [
	{name = "Christoph M. Konrad", email = "c.m.konrad@tudelft.nl"},
	{name = "Anna Marbus"}
]
requires-python = ">3.11"
dependencies = [
	"numpy",
	"sympy",
	"matplotlib",
	"scipy",
	"datetime",
	"pandas",
	"scikit-learn",
	"filterpy",
	"bicycleparameters",
	"pyarrow",
	"trajdatamanager"
]


[project.optional-dependencies]
cl2000 = [
	"cantools"
]
canedge2 = [
	"asammdf"
]

[project.scripts]
decodecan = "sensorbike.scripts.decode_can:main"
	
[tool.setuptools.packages.find]
where = ["src"]  

