"""
Decode a CAN-bus mf4 file and export kinematic measurements to csv or parquet.
Can process individual files or search directories for mf4 files.

Usage:

python decode_can.py [-h] -d DBC -l LOGS [-a] [-nr] [-i] [-o OUTDIR] [-f {.csv,.parquet}] [-m]

@author: Christoph M. Konrad
"""

import os
import argparse
import sensorbike.canbus as can
import pandas as pd
import warnings
from datetime import datetime

def parse_args():

    parser = argparse.ArgumentParser(prog='decode_can.py',
                                     description='Decode one or multiple CAN logs and export the kinematic measurements to .csv')
    parser.add_argument('-d', '--dbc', type=str, help='File path to the CAN bus definition file (.dbc file)', required= True)
    parser.add_argument('-l', '--logs', type=str, help=('File path of a single CAN log file or a '
                                                        'directory which contains log files. If a directory is'
                                                        ' supplied, the directory and all subdirectories will '
                                                        'be searched for .mf4 (CANEdge2) and .txt (CL2000) log files.'), required=True)
    parser.add_argument('-a', '--append', action='store_true', help=('If True, multiple can log files will be '
                                                        'appended to the same .csv. in alphabetical order. Only '
                                                        'select if files are consecutive! Otherwise, an individual '
                                                        '.csv file will be created for each log file.'))
    parser.add_argument('-nr', '--nonrecursive', action='store_true', help=('Perform non-recursive search exclusively in '
                        'the specified directory instead of recursive search through all subdirectories. Has no effect if '
                        'a specific file is given instead of a directory.'))
    parser.add_argument('-i', '--ignoreexisting', action='store_true', help='Ignore logs for which a decoded file already exists.')
    parser.add_argument('-o', '--outdir', type=str, default='input directory', help='The output directory')
    parser.add_argument('-f', '--format', choices=['.csv', '.parquet'], default = '.csv',
                        help=('Output format. Choose ".csv" for human-readible files or ".parquet" for'
                              'memory efficiency.'))
    parser.add_argument('-k', '--keys', choices=['kinematics', 'messages', 'all'], default='kinematics',
                        help=("Data keys to extract from the log. 'kinematics' extracts only kinematic data. 'messages'"
                              " extracts only system status messages. 'all' extracts both."))
    parser.add_argument('-m', '--mute', action='store_true', help='Mutes verbosity.')
    
    return parser.parse_args()
    
def summarize(fname, df):
    """ Create a summary of the dataframe."""

    summary = df.median(numeric_only=True).add_suffix("_median")
    summary.loc['file'] = fname
    summary.loc['n_samples'] = len(df)
    summary.loc['n_samples_na'] = df.select_dtypes(include="number").isna().all(axis=1).sum()

    return summary

def write_decode_log(dir_out, df_summary, args, empty, failed):

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = os.path.join(dir_out, f"{timestamp}_can-decoding-log.txt")

    with open(filepath, "w") as f:
        f.write("CAN decoding log\n")
        f.write("Generated by: decode_can.py\n")
        f.write(f"Timestamp: {timestamp}\n\n")

        f.write("Settings:\n")
        f.write(f"    input directory:  ../{os.path.basename(args.logs)}\n")
        f.write(f"    output directory: ../{os.path.basename(dir_out)}\n")
        f.write(f"    dbc-filename:     {os.path.basename(args.dbc)}\n")
        f.write(f"    append:           {args.append}\n")
        f.write(f"    nonrecursive:     {args.nonrecursive}\n")
        f.write(f"    ignoreexisting:   {args.ignoreexisting}\n")
        f.write(f"    format:           {args.format}\n")
        f.write(f"    keys:             {args.keys}\n\n")

        f.write("Decoding Summary:\n")
        f.write(f"   n_files:  {len(df_summary)}\n")
        f.write(f"   n_empty:  {len(empty)}\n")
        f.write(f"   n_failed: {len(failed)}\n\n")

        if len(empty) > 0:
            f.write("Empty Files:\n")
            for fname in empty:
                f.write(f"    {fname}\n")
            f.write("\n")
        
        if len(failed) > 0:
            f.write("Decoding Failed:\n")
            for fname in failed:
                f.write(f"    {fname}\n")
            f.write("\n")

        f.write("Data Summary:\n")
        f.write(df_summary.to_string(index=True))


def write(dir_out, df, fname_out, format, verbose):

    # filepath for writing
    if not os.path.isdir(dir_out):
        os.makedirs(dir_out)
        if verbose:
            print(f'   Created missing output directory {dir_out}')
    
    if not fname_out.endswith(format):
        fname_out += format

    filepath_out = os.path.join(dir_out, fname_out)
    if verbose:
        print(f'   ---> {filepath_out}')

    # save
    if format == '.csv':
        df.to_csv(filepath_out, sep=';')
    else:
        df.to_parquet(filepath_out, engine="pyarrow", compression="snappy")


def main():

    args = parse_args()

    # set up file paths
    filepath_dbc = can.verify_filepath_dbc(args.dbc)

    filepaths_logs = []
    if os.path.isdir(args.logs):
        filepaths_mf4logs_rel, filepath_txtlogs_rel = can.list_canlogs(args.logs, verbose=not args.mute, 
                                                                       nonrecursive=args.nonrecursive,
                                                                       ignoreexisiting=args.ignoreexisting, 
                                                                       filetypes_out=[args.format])
        filepaths_logs_rel = filepaths_mf4logs_rel+filepath_txtlogs_rel
        filepaths_logs = [os.path.join(args.logs, f) for f in filepaths_logs_rel]
        if len(filepaths_logs)==0:
             raise FileNotFoundError(f"No CAN logs found in {args.logs}!")
    else:
        filepaths_logs = [can.verify_filepath_can(args.logs)]
        if not args.mute:
            print(f"Found 1 log file:")
            print(f"      1: {filepaths_logs[0]}")

            if args.nonrecursive:
                warnings.warn((f"Non-recursive option ('-nr'/'--nonrecursive') has no effect because "
                "--logs/-l points to a single log file instead of a directory."))

    # output directories
    if args.outdir == 'input directory':
        dir_out_root = args.logs
        dirs_out = [os.path.dirname(f) for f in filepaths_logs]
    else:
        dir_out_root = args.outdir
        dirs_out = []
        for f in filepaths_logs:
            rel_path = os.path.relpath(os.path.dirname(f), start=args.logs)
            if rel_path == ".":
                dirs_out.append(args.outdir)
            else:
                dirs_out.append(os.path.join(args.outdir, rel_path)) 

    # output names
    filenames_out = []
    for f in filepaths_logs:
        filename_out = os.path.splitext(os.path.basename(f))[0]
        filename_out += "_" + args.keys + args.format
        filenames_out.append(filename_out)


    # decode can files
    df_list = []
    if not args.mute:
        if args.append:
            print("Decoding ...")
        else:
            print("Decoding and writing ...")

    n_empty = 0
    n_failed = 0
    failed = []
    empty = []
    summary = [] 
    for dir_out, f, fname_out in zip(dirs_out, filepaths_logs, filenames_out):
            rel_filepath = os.path.relpath(os.path.join(dir_out, fname_out), start=dir_out_root)
            print(f"   {f}")
        
            df_i = can.process_can(f, filepath_dbc)

            if df_i.shape[0] < 1:
                print(f"Logfile '{f}' was empty!")
                n_empty += 1
                empty.append(rel_filepath)
                continue
            
            try:
                df_i = can.extract_canlog_columns(df_i, args.keys)
            except KeyError:
                failed.append(rel_filepath)
                n_failed += 1
                continue

            if args.append:
                df_list.append(df_i)
            else:
                rel_filepath = os.path.relpath(os.path.join(dir_out, fname_out), start=dir_out_root)
                summary.append(summarize(rel_filepath, df_i))
                write(dir_out, df_i, fname_out, args.format, not args.mute)
    summary = pd.concat(summary, axis=1)
    write_decode_log(dir_out_root, summary, args, empty, failed)
                
    if n_empty >= len(filepaths_logs):
        print(f"All logfiles were empty!")
        return
    
    # append
    if args.append and len(df_list > 1):

        if not args.mute:
            print("   Appending logs ... ")

        # Warn
        if len(df_list) > 1 and not args.mute:
            print((f"WARNING: Concatenating multiple log files in alphabetical order."
                f" This only makes sense if the log files contain directly consecutive"
                f" logs without breaks! Consider converting individual files if unsure."))

        df_app = pd.concat(df_list, ignore_index=True)
        if not args.mute:
            print("   done!")


        if not args.mute:
            print("Write ...")

        # out directory
        if args.outdir == 'input directory':
            dir_out = args.logs
        else: 
            dir_out = dirs_out[0]

        write(dir_out, df_app, f"{os.path.splitext(filenames_out[0])[0]}-{os.path.splitext(filenames_out[-1])[0]}")

        if not args.mute:
            print("   done!")


if __name__ == "__main__":
    main()